In [3]:
a = input().split(',')

2,3,4


['2', '3', '4']

In [27]:
wordsdict = {}  # key will be word and its synonyms will be a list

# 1 means you need to add word and synonyms in a list
# 2 means you need to print the word and its sysnonyms in alphabatical order

totalnumberofactions = int(input())

overalllist = []
overalllist.append(totalnumberofactions)
for i in range(totalnumberofactions):
    temp = input().split(',')
    overalllist.append([int(temp[0]),temp[1:]])
    
    if temp[1] in wordsdict:
        wordsdict[temp[1]].append(temp[2:])
    else:
        if wordsdict.items():
            for key,value in wordsdict.items():
                if temp[1] in value:
                    wordsdict[key].append(temp[1:])
                    continue

        else:
            wordsdict[temp[1]] = []
            wordsdict[temp[1]].append(temp[2:])
            continue

3
1,amit,meel
2,dfg,fhgf


RuntimeError: dictionary changed size during iteration

In [25]:
overalllist

[3, [1, ['amit', 'meel']], [2, ['dg', 'gdfg']], [1, ['amit']]]

In [26]:
wordsdict

{'amit': [['meel'], []]}

In [ ]:
for listofwords in overalllist:
    if listofwords[0]==1:
        continue
    elif listofwords[0]==2:
        word = listofwords[1]
        
    else:
        print('please type the correct  action)

In [3]:
c= {'a':[10,12,24],
10:[40,50]}

In [11]:
list(c.keys())

['a', 10]

In [12]:
list(c.values())

[[10, 12, 24], [40, 50]]

True

In [20]:
a= {}
for k,v in c.items():
    print(k,v)


a [10, 12, 24]
10 [40, 50]


In [21]:
c.items()

dict_items([('a', [10, 12, 24]), (10, [40, 50])])

In [28]:
totalnumberofactions = int(input())

overalllist = []
overalllist.append(totalnumberofactions)
for i in range(totalnumberofactions):
    temp = input().split(',')
    overalllist.append([int(temp[0]),temp[1:]])

2
1,qmi,dfgfd
2,dgdf,fghgfh


In [31]:
for i,listofvalues in enumerate(overalllist[1:]):
    print(i,listofvalues)

0 [1, ['qmi', 'dfgfd']]
1 [2, ['dgdf', 'fghgfh']]


In [ ]:

1. Sort the words by length: the longest word first.
2. If the length of two words is the same, compare the first letter of both the words. The letter that is lower on the lexicographical order is placed above the one that appears higher on the order.

3. If a tie still exists, then compare the last letters. The letter that is lower on the lexicographical order is placed above the one that appears higher on the order.

4. If a tie still exists, compare the second letters. The letter that is lower on the lexicographical order is placed above the one that appears higher on the order

5. If a tie still exists, compare the second last letters. The letter that is lower on the lexicographical order is placed above the one that appears higher on the order

6. And so on.

In [314]:
inputwords = ['laptop',   'Mobile',   'moaile',   'mobize', 'Car']

In [315]:
inputwords = sorted(inputwords,key=len,reverse=True)

In [316]:
inputwords

['laptop', 'Mobile', 'moaile', 'mobize', 'Car']

In [306]:
outputwords = inputwords

In [307]:
['laptop', 'moaile', 'Mobile', 'mobize', 'Car']



['laptop', 'moaile', 'Mobile', 'mobize', 'Car']

In [312]:
jth = 0
for i in range(len(inputwords)):
    if jth<len(inputwords)-1:
        ith = i
    #     ith = inputwords[i]
        jth = i+1
    #     jth = inputwords[i+1]
#         print(jth)
        if (inputwords[ith][0] != inputwords[jth][0]) and (inputwords[ith][0].lower() != inputwords[jth][0].lower()):
            temp = sorted([inputwords[ith],inputwords[jth]], reverse = True)
            outputwords[ith] = temp[0]
            outputwords[jth] = temp[1]
        elif inputwords[ith][0] == inputwords[jth][0]:
            temp = sorted([inputwords[ith],inputwords[jth]])
            outputwords[ith] = temp[0]
            outputwords[jth] = temp[1]
            
        elif (inputwords[ith][0] != inputwords[jth][0]) and  (inputwords[ith][0].lower() == inputwords[jth][0].lower()):
            temp = sorted([inputwords[ith],inputwords[jth]], reverse = True)
            outputwords[ith] = temp[0]
            outputwords[jth] = temp[1]
    

In [313]:
outputwords

['laptop', 'moaile', 'moaile', 'mobize', 'Car']

In [274]:
sorted(['laptop', 'Mobile'],reverse=True)

['laptop', 'Mobile']

In [84]:
inputwords

['laptop', 'Mobile', 'moaile', 'mobize', 'Car']

In [86]:
sorted(['Mobile', 'moaile'],reverse=True)

['moaile', 'Mobile']

False

In [91]:
def function(inputwords):
    jth = 0
    for i in range(len(inputwords)):
        if jth<len(inputwords):
            ith = i
        #     ith = inputwords[i]
            jth = i+1
        #     jth = inputwords[i+1]
            print(jth)
            if inputwords[ith][0] != inputwords[jth][0]:
                temp = sorted([inputwords[ith],inputwords[jth]], reverse = True)
                inputwords[ith] = temp[0]
                inputwords[jth] = temp[1]
            elif inputwords[ith][0] == inputwords[jth][0]:
                temp = sorted([inputwords[ith],inputwords[jth]])
                inputwords[ith] = temp[0]
                inputwords[jth] = temp[1]
    

In [92]:
function(inputwords)

1
2
3
4
5


IndexError: list index out of range

In [94]:
'a'.upper()

'A'

In [254]:
_string= "0 ssd -3 23e -2 oas 1 -4 -2 red -3 4 green 1"

In [255]:
import re

regex = re.compile('(\s\d*[a-zA-Z]+\s)')
#First parameter is the replacement, second parameter is your input string
inputstring = regex.sub(' ', _string)

In [256]:
inputstring

'0 -3 -2 1 -4 -2 -3 4 1'

In [178]:
# numbers = re.findall(r'(\s\d*[a-zA-Z]+\s)',_string)

In [179]:
# numbers

In [180]:
# inputstring = inputstring.replace('  ',' ')

In [181]:
# inputstring

In [182]:
listinput = list(map(float,inputstring.split(' ')))

In [183]:
listinput

[0.0, -3.0, -2.0, 1.0, -4.0, -2.0, -3.0, 4.0, 1.0]

In [184]:
col = 3

In [185]:
maininput = [listinput[i:i+col] for i in range(0, len(listinput), col)]

In [186]:
maininput

[[0.0, -3.0, -2.0], [1.0, -4.0, -2.0], [-3.0, 4.0, 1.0]]

False

In [218]:
def transposeMatrix(m):
    return map(list,zip(*m))

def getMatrixMinor(m,i,j):
    return [row[:j] + row[j+1:] for row in (m[:i]+m[i+1:])]

def getMatrixDeternminant(m):
    #base case for 2x2 matrix
    if len(m) == 2:
        return m[0][0]*m[1][1]-m[0][1]*m[1][0]

    determinant = 0
    for c in range(len(m)):
        determinant += ((-1)**c)*m[0][c]*getMatrixDeternminant(getMatrixMinor(m,0,c))
    return determinant

def getMatrixInverse(m):
    determinant = getMatrixDeternminant(m)
    #special case for 2x2 matrix:
    if len(m) == 2:
        return [[m[1][1]/determinant, -1*m[0][1]/determinant],
                [-1*m[1][0]/determinant, m[0][0]/determinant]]

    #find matrix of cofactors
    cofactors = []
    for r in range(len(m)):
        cofactorRow = []
        for c in range(len(m)):
            minor = getMatrixMinor(m,r,c)
            cofactorRow.append(((-1)**(r+c)) * getMatrixDeternminant(minor))
        cofactors.append(cofactorRow)
    cofactors = transposeMatrix(cofactors)
    cofactors = list(cofactors)
    for r in range(len(cofactors)):
        for c in range(len(cofactors)):
            cofactors[r][c] = cofactors[r][c]/determinant
    return cofactors

In [251]:
inverse_matrix = getMatrixInverse(maininput)
print(inverse_matrix)

[[4.0, -5.0, -2.0], [5.0, -6.0, -2.0], [-8.0, 9.0, 3.0]]


In [252]:
for list_ in inverse_matrix:
    print(list_)
    for i,element in enumerate(list_):
        if element<0:
            list_[i] = str(element).ljust(5,'0')
        else:
            list_[i] = str(element).ljust(4,'0')

[4.0, -5.0, -2.0]
[5.0, -6.0, -2.0]
[-8.0, 9.0, 3.0]


In [253]:
inverse_matrix

[['4.00', '-5.00', '-2.00'],
 ['5.00', '-6.00', '-2.00'],
 ['-8.00', '9.00', '3.00']]

In [222]:
y

array([[ 4., -5., -2.],
       [ 5., -6., -2.],
       [-8.,  9.,  3.]])

In [222]:
y

array([[ 4., -5., -2.],
       [ 5., -6., -2.],
       [-8.,  9.,  3.]])

In [222]:
y

array([[ 4., -5., -2.],
       [ 5., -6., -2.],
       [-8.,  9.,  3.]])

In [223]:
a = [[1,2,3,4],[4,5,6,3],[6,7,8,5],[3,4,5,6]]

ZeroDivisionError: division by zero

In [216]:
y = np.linalg.inv(a) 

In [275]:
'A'.lower()

'a'